const actionType = {
    GET_ALLHOME: 'GET_ALLHOME',
    GET_ALLCITIES: 'GET_ALLCITIES',
    GET_HOMESBYCITYNAME: 'GET_HOMESBYCITYNAME',
    GET_HOTELBYID: 'GET_HOTELBYID',
    GET_ROOMSBYIDHOTEL: 'GET_ROOMSBYIDHOTEL',
    GET_TYPEROOMS: 'GET_TYPEROOMS',
    GET_ROOMBYID: 'GET_ROOMBYID',
    POST_CREATENEWBOOKING: 'POST_CREATENEWBOOKING'
}
export default actionType